# fly.toml app configuration file generated for white-mountain-6577 on 2023-10-21T19:06:59+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "white-mountain-6577"
primary_region = "syd"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
