GET http://localhost:3001/api/contacts/

###
GET http://localhost:3001/api/contacts/6533b6b4fee0f594b6be0706


###
HEAD http://localhost:3001/api/contacts/ HTTP/1.1 

###
POST http://localhost:3001/api/contacts/ HTTP/1.1
content-type: application/json

{
    "name": "test person",
    "number": "10-22-334455"
}

###
PUT http://localhost:3001/api/contacts/653487b07cb7f01c09d768fa HTTP/1.1
content-type: application/json

{
    "name": "PU",
    "number": "111-123456"
}

###
DELETE http://localhost:3001/api/contacts/65345a78ce708ecb8f936da1 HTTP/1.1
content-type: application/json


// To Fly.io
//https://white-mountain-6577.fly.dev/api/contacts/1
###

POST https://white-mountain-6577.fly.dev/api/contacts HTTP/1.1
content-type: application/json

{

    "name": "Sample name",
    "number": "999-123456"
  
}
