GET http://localhost:3001/api/contacts/

###
GET http://localhost:3001/api/contactsBAD/20


###
HEAD http://localhost:3001/api/contacts/ HTTP/1.1 

###
POST http://localhost:3001/api/contacts/ HTTP/1.1
content-type: application/json

{

    "name": "Sample name",
    "number": "999-123456"
  
}

###
DELETE http://localhost:3001/api/contacts/2 HTTP/1.1
content-type: application/json
